# Generated by Django 2.2.7 on 2019-12-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='img_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
