# Generated by Django 2.2.7 on 2019-12-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191207_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='AddSlider',
        ),
    ]
